# Update interval in seconds (will be converted to ticks internally: 1 second = 20 ticks)
update_interval: 20 # Spawner action interval in seconds

# Messages
messages:
  wrong_position: "You can't place the Spawner here!"
  no_permission: "You do not own this OreSpawner to be able to break it!"

# Types of OreSpawner
ore_spawner_types:
  coal:
    item_data:
      item: "minecraft:black_glazed_terracotta"
      name: "Coal Ore"
      lore:
        - "Coal Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:coal_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  diamond:
    item_data:
      item: "minecraft:light_blue_glazed_terracotta"
      name: "Diamond Ore"
      lore:
        - "Diamond Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:diamond_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  emerald:
    item_data:
      item: "minecraft:lime_glazed_terracotta"
      name: "Emerald Ore"
      lore:
        - "Emerald Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:emerald_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  lapis:
    item_data:
      item: "minecraft:blue_glazed_terracotta"
      name: "Lapis lazuli Ore"
      lore:
        - "Lapis Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:lapis_lazuli_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  redstone:
    item_data:
      item: "minecraft:red_glazed_terracotta"
      name: "Redstone Ore"
      lore:
        - "Redstone Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:redstone_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  gold:
    item_data:
      item: "minecraft:yellow_glazed_terracotta"
      name: "Gold Ore"
      lore:
        - "Gold Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:gold_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  iron:
    item_data:
      item: "minecraft:light_gray_glazed_terracotta"
      name: "Iron Ore"
      lore:
        - "Gold Ore"
        - "Level: %level%"

    blocks:
      - "minecraft:iron_ore"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3

  cobblestone:
    item_data:
      item: "minecraft:gray_glazed_terracotta"
      name: "Cobblestone"
      lore:
        - "Cobblestone"
        - "Level: %level%"

    blocks:
      - "minecraft:cobblestone"

    levels:
      1:
        speed: 1
      2:
        speed: 2
      3:
        speed: 3